#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnverifiedBlast
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hldemailmgmt")]
	public partial class ASCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWarmingEmailList(WarmingEmailList instance);
    partial void UpdateWarmingEmailList(WarmingEmailList instance);
    partial void DeleteWarmingEmailList(WarmingEmailList instance);
    partial void InsertList_ID_1908_for_Ardent(List_ID_1908_for_Ardent instance);
    partial void UpdateList_ID_1908_for_Ardent(List_ID_1908_for_Ardent instance);
    partial void DeleteList_ID_1908_for_Ardent(List_ID_1908_for_Ardent instance);
    #endregion
		
		public ASCDataContext() : 
				base(global::UnverifiedBlast.Properties.Settings.Default.hldemailmgmtConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ASCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ASCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ASCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ASCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WarmingEmailList> WarmingEmailLists
		{
			get
			{
				return this.GetTable<WarmingEmailList>();
			}
		}
		
		public System.Data.Linq.Table<List_ID_1908_for_Ardent> List_ID_1908_for_Ardents
		{
			get
			{
				return this.GetTable<List_ID_1908_for_Ardent>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WarmingEmailList")]
	public partial class WarmingEmailList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Email;
		
		private string _Profession;
		
		private string _Specialty;
		
		private string _Phone;
		
		private bool _DoNotEmail;
		
		private bool _CandidateOptOut;
		
		private bool _BadEmail;
		
		private bool _SignedUp;
		
		private System.Nullable<System.DateTime> _LastEmailed;
		
		private System.Nullable<int> _TimesEmailed;
		
		private System.Nullable<System.DateTime> _LastClicked;
		
		private System.Nullable<System.DateTime> _LastOpened;
		
		private string _GUID;
		
		private string _LastEmailedHost;
		
		private string _TypeOfHost;
		
		private System.Nullable<bool> _Quarantined;
		
		private System.Nullable<bool> _DoubleQuarantine;
		
		private System.Nullable<System.DateTime> _LastUsageDate;
		
		private System.Nullable<bool> _sellable;
		
		private System.Nullable<bool> _HealthLink;
		
		private string _emailSource;
		
		private string _emailSourceSubType;
		
		private System.Nullable<long> _HLDProvID;
		
		private System.Nullable<int> _HLDEmailID;
		
		private string _WebbulaFlag;
		
		private string _StateAbbrev;
		
		private System.Nullable<bool> _IsDuplicate;
		
		private System.Nullable<bool> _AbuseFlag;
		
		private System.Nullable<System.DateTime> _AbuseLogged;
		
		private System.Nullable<bool> _Active;
		
		private System.Nullable<System.DateTime> _CreatedOn;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _ModifiedOn;
		
		private string _ModifiedBy;
		
		private System.Nullable<System.DateTime> _DeactivateddOn;
		
		private string _DeactivateddBy;
		
		private string _Notes;
		
		private System.Nullable<bool> _IsGoodEmail;
		
		private System.Nullable<decimal> _HLDEmailRating;
		
		private System.Nullable<System.DateTime> _HLDPermissionDate;
		
		private System.Nullable<System.DateTime> _HLDVerificationDate;
		
		private System.Nullable<System.DateTime> _HLDEmailSent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnProfessionChanging(string value);
    partial void OnProfessionChanged();
    partial void OnSpecialtyChanging(string value);
    partial void OnSpecialtyChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnDoNotEmailChanging(bool value);
    partial void OnDoNotEmailChanged();
    partial void OnCandidateOptOutChanging(bool value);
    partial void OnCandidateOptOutChanged();
    partial void OnBadEmailChanging(bool value);
    partial void OnBadEmailChanged();
    partial void OnSignedUpChanging(bool value);
    partial void OnSignedUpChanged();
    partial void OnLastEmailedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastEmailedChanged();
    partial void OnTimesEmailedChanging(System.Nullable<int> value);
    partial void OnTimesEmailedChanged();
    partial void OnLastClickedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastClickedChanged();
    partial void OnLastOpenedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastOpenedChanged();
    partial void OnGUIDChanging(string value);
    partial void OnGUIDChanged();
    partial void OnLastEmailedHostChanging(string value);
    partial void OnLastEmailedHostChanged();
    partial void OnTypeOfHostChanging(string value);
    partial void OnTypeOfHostChanged();
    partial void OnQuarantinedChanging(System.Nullable<bool> value);
    partial void OnQuarantinedChanged();
    partial void OnDoubleQuarantineChanging(System.Nullable<bool> value);
    partial void OnDoubleQuarantineChanged();
    partial void OnLastUsageDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUsageDateChanged();
    partial void OnsellableChanging(System.Nullable<bool> value);
    partial void OnsellableChanged();
    partial void OnHealthLinkChanging(System.Nullable<bool> value);
    partial void OnHealthLinkChanged();
    partial void OnemailSourceChanging(string value);
    partial void OnemailSourceChanged();
    partial void OnemailSourceSubTypeChanging(string value);
    partial void OnemailSourceSubTypeChanged();
    partial void OnHLDProvIDChanging(System.Nullable<long> value);
    partial void OnHLDProvIDChanged();
    partial void OnHLDEmailIDChanging(System.Nullable<int> value);
    partial void OnHLDEmailIDChanged();
    partial void OnWebbulaFlagChanging(string value);
    partial void OnWebbulaFlagChanged();
    partial void OnStateAbbrevChanging(string value);
    partial void OnStateAbbrevChanged();
    partial void OnIsDuplicateChanging(System.Nullable<bool> value);
    partial void OnIsDuplicateChanged();
    partial void OnAbuseFlagChanging(System.Nullable<bool> value);
    partial void OnAbuseFlagChanged();
    partial void OnAbuseLoggedChanging(System.Nullable<System.DateTime> value);
    partial void OnAbuseLoggedChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    partial void OnCreatedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnModifiedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedOnChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnDeactivateddOnChanging(System.Nullable<System.DateTime> value);
    partial void OnDeactivateddOnChanged();
    partial void OnDeactivateddByChanging(string value);
    partial void OnDeactivateddByChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnIsGoodEmailChanging(System.Nullable<bool> value);
    partial void OnIsGoodEmailChanged();
    partial void OnHLDEmailRatingChanging(System.Nullable<decimal> value);
    partial void OnHLDEmailRatingChanged();
    partial void OnHLDPermissionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHLDPermissionDateChanged();
    partial void OnHLDVerificationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnHLDVerificationDateChanged();
    partial void OnHLDEmailSentChanging(System.Nullable<System.DateTime> value);
    partial void OnHLDEmailSentChanged();
    #endregion
		
		public WarmingEmailList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profession", DbType="VarChar(16)")]
		public string Profession
		{
			get
			{
				return this._Profession;
			}
			set
			{
				if ((this._Profession != value))
				{
					this.OnProfessionChanging(value);
					this.SendPropertyChanging();
					this._Profession = value;
					this.SendPropertyChanged("Profession");
					this.OnProfessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specialty", DbType="VarChar(50)")]
		public string Specialty
		{
			get
			{
				return this._Specialty;
			}
			set
			{
				if ((this._Specialty != value))
				{
					this.OnSpecialtyChanging(value);
					this.SendPropertyChanging();
					this._Specialty = value;
					this.SendPropertyChanged("Specialty");
					this.OnSpecialtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoNotEmail", DbType="Bit NOT NULL")]
		public bool DoNotEmail
		{
			get
			{
				return this._DoNotEmail;
			}
			set
			{
				if ((this._DoNotEmail != value))
				{
					this.OnDoNotEmailChanging(value);
					this.SendPropertyChanging();
					this._DoNotEmail = value;
					this.SendPropertyChanged("DoNotEmail");
					this.OnDoNotEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CandidateOptOut", DbType="Bit NOT NULL")]
		public bool CandidateOptOut
		{
			get
			{
				return this._CandidateOptOut;
			}
			set
			{
				if ((this._CandidateOptOut != value))
				{
					this.OnCandidateOptOutChanging(value);
					this.SendPropertyChanging();
					this._CandidateOptOut = value;
					this.SendPropertyChanged("CandidateOptOut");
					this.OnCandidateOptOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BadEmail", DbType="Bit NOT NULL")]
		public bool BadEmail
		{
			get
			{
				return this._BadEmail;
			}
			set
			{
				if ((this._BadEmail != value))
				{
					this.OnBadEmailChanging(value);
					this.SendPropertyChanging();
					this._BadEmail = value;
					this.SendPropertyChanged("BadEmail");
					this.OnBadEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SignedUp", DbType="Bit NOT NULL")]
		public bool SignedUp
		{
			get
			{
				return this._SignedUp;
			}
			set
			{
				if ((this._SignedUp != value))
				{
					this.OnSignedUpChanging(value);
					this.SendPropertyChanging();
					this._SignedUp = value;
					this.SendPropertyChanged("SignedUp");
					this.OnSignedUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEmailed", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastEmailed
		{
			get
			{
				return this._LastEmailed;
			}
			set
			{
				if ((this._LastEmailed != value))
				{
					this.OnLastEmailedChanging(value);
					this.SendPropertyChanging();
					this._LastEmailed = value;
					this.SendPropertyChanged("LastEmailed");
					this.OnLastEmailedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimesEmailed", DbType="Int")]
		public System.Nullable<int> TimesEmailed
		{
			get
			{
				return this._TimesEmailed;
			}
			set
			{
				if ((this._TimesEmailed != value))
				{
					this.OnTimesEmailedChanging(value);
					this.SendPropertyChanging();
					this._TimesEmailed = value;
					this.SendPropertyChanged("TimesEmailed");
					this.OnTimesEmailedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastClicked", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastClicked
		{
			get
			{
				return this._LastClicked;
			}
			set
			{
				if ((this._LastClicked != value))
				{
					this.OnLastClickedChanging(value);
					this.SendPropertyChanging();
					this._LastClicked = value;
					this.SendPropertyChanged("LastClicked");
					this.OnLastClickedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastOpened", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastOpened
		{
			get
			{
				return this._LastOpened;
			}
			set
			{
				if ((this._LastOpened != value))
				{
					this.OnLastOpenedChanging(value);
					this.SendPropertyChanging();
					this._LastOpened = value;
					this.SendPropertyChanged("LastOpened");
					this.OnLastOpenedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUID", DbType="Char(32)")]
		public string GUID
		{
			get
			{
				return this._GUID;
			}
			set
			{
				if ((this._GUID != value))
				{
					this.OnGUIDChanging(value);
					this.SendPropertyChanging();
					this._GUID = value;
					this.SendPropertyChanged("GUID");
					this.OnGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastEmailedHost", DbType="NVarChar(50)")]
		public string LastEmailedHost
		{
			get
			{
				return this._LastEmailedHost;
			}
			set
			{
				if ((this._LastEmailedHost != value))
				{
					this.OnLastEmailedHostChanging(value);
					this.SendPropertyChanging();
					this._LastEmailedHost = value;
					this.SendPropertyChanged("LastEmailedHost");
					this.OnLastEmailedHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfHost", DbType="NVarChar(1)")]
		public string TypeOfHost
		{
			get
			{
				return this._TypeOfHost;
			}
			set
			{
				if ((this._TypeOfHost != value))
				{
					this.OnTypeOfHostChanging(value);
					this.SendPropertyChanging();
					this._TypeOfHost = value;
					this.SendPropertyChanged("TypeOfHost");
					this.OnTypeOfHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quarantined", DbType="Bit")]
		public System.Nullable<bool> Quarantined
		{
			get
			{
				return this._Quarantined;
			}
			set
			{
				if ((this._Quarantined != value))
				{
					this.OnQuarantinedChanging(value);
					this.SendPropertyChanging();
					this._Quarantined = value;
					this.SendPropertyChanged("Quarantined");
					this.OnQuarantinedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoubleQuarantine", DbType="Bit")]
		public System.Nullable<bool> DoubleQuarantine
		{
			get
			{
				return this._DoubleQuarantine;
			}
			set
			{
				if ((this._DoubleQuarantine != value))
				{
					this.OnDoubleQuarantineChanging(value);
					this.SendPropertyChanging();
					this._DoubleQuarantine = value;
					this.SendPropertyChanged("DoubleQuarantine");
					this.OnDoubleQuarantineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUsageDate", DbType="Date")]
		public System.Nullable<System.DateTime> LastUsageDate
		{
			get
			{
				return this._LastUsageDate;
			}
			set
			{
				if ((this._LastUsageDate != value))
				{
					this.OnLastUsageDateChanging(value);
					this.SendPropertyChanging();
					this._LastUsageDate = value;
					this.SendPropertyChanged("LastUsageDate");
					this.OnLastUsageDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sellable", DbType="Bit")]
		public System.Nullable<bool> sellable
		{
			get
			{
				return this._sellable;
			}
			set
			{
				if ((this._sellable != value))
				{
					this.OnsellableChanging(value);
					this.SendPropertyChanging();
					this._sellable = value;
					this.SendPropertyChanged("sellable");
					this.OnsellableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthLink", DbType="Bit")]
		public System.Nullable<bool> HealthLink
		{
			get
			{
				return this._HealthLink;
			}
			set
			{
				if ((this._HealthLink != value))
				{
					this.OnHealthLinkChanging(value);
					this.SendPropertyChanging();
					this._HealthLink = value;
					this.SendPropertyChanged("HealthLink");
					this.OnHealthLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailSource", DbType="NVarChar(1)")]
		public string emailSource
		{
			get
			{
				return this._emailSource;
			}
			set
			{
				if ((this._emailSource != value))
				{
					this.OnemailSourceChanging(value);
					this.SendPropertyChanging();
					this._emailSource = value;
					this.SendPropertyChanged("emailSource");
					this.OnemailSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailSourceSubType", DbType="VarChar(128)")]
		public string emailSourceSubType
		{
			get
			{
				return this._emailSourceSubType;
			}
			set
			{
				if ((this._emailSourceSubType != value))
				{
					this.OnemailSourceSubTypeChanging(value);
					this.SendPropertyChanging();
					this._emailSourceSubType = value;
					this.SendPropertyChanged("emailSourceSubType");
					this.OnemailSourceSubTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLDProvID", DbType="BigInt")]
		public System.Nullable<long> HLDProvID
		{
			get
			{
				return this._HLDProvID;
			}
			set
			{
				if ((this._HLDProvID != value))
				{
					this.OnHLDProvIDChanging(value);
					this.SendPropertyChanging();
					this._HLDProvID = value;
					this.SendPropertyChanged("HLDProvID");
					this.OnHLDProvIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLDEmailID", DbType="Int")]
		public System.Nullable<int> HLDEmailID
		{
			get
			{
				return this._HLDEmailID;
			}
			set
			{
				if ((this._HLDEmailID != value))
				{
					this.OnHLDEmailIDChanging(value);
					this.SendPropertyChanging();
					this._HLDEmailID = value;
					this.SendPropertyChanged("HLDEmailID");
					this.OnHLDEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebbulaFlag", DbType="NVarChar(50)")]
		public string WebbulaFlag
		{
			get
			{
				return this._WebbulaFlag;
			}
			set
			{
				if ((this._WebbulaFlag != value))
				{
					this.OnWebbulaFlagChanging(value);
					this.SendPropertyChanging();
					this._WebbulaFlag = value;
					this.SendPropertyChanged("WebbulaFlag");
					this.OnWebbulaFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateAbbrev", DbType="NVarChar(2)")]
		public string StateAbbrev
		{
			get
			{
				return this._StateAbbrev;
			}
			set
			{
				if ((this._StateAbbrev != value))
				{
					this.OnStateAbbrevChanging(value);
					this.SendPropertyChanging();
					this._StateAbbrev = value;
					this.SendPropertyChanged("StateAbbrev");
					this.OnStateAbbrevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDuplicate", DbType="Bit")]
		public System.Nullable<bool> IsDuplicate
		{
			get
			{
				return this._IsDuplicate;
			}
			set
			{
				if ((this._IsDuplicate != value))
				{
					this.OnIsDuplicateChanging(value);
					this.SendPropertyChanging();
					this._IsDuplicate = value;
					this.SendPropertyChanged("IsDuplicate");
					this.OnIsDuplicateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbuseFlag", DbType="Bit")]
		public System.Nullable<bool> AbuseFlag
		{
			get
			{
				return this._AbuseFlag;
			}
			set
			{
				if ((this._AbuseFlag != value))
				{
					this.OnAbuseFlagChanging(value);
					this.SendPropertyChanging();
					this._AbuseFlag = value;
					this.SendPropertyChanged("AbuseFlag");
					this.OnAbuseFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbuseLogged", DbType="DateTime")]
		public System.Nullable<System.DateTime> AbuseLogged
		{
			get
			{
				return this._AbuseLogged;
			}
			set
			{
				if ((this._AbuseLogged != value))
				{
					this.OnAbuseLoggedChanging(value);
					this.SendPropertyChanging();
					this._AbuseLogged = value;
					this.SendPropertyChanged("AbuseLogged");
					this.OnAbuseLoggedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this._ModifiedOn;
			}
			set
			{
				if ((this._ModifiedOn != value))
				{
					this.OnModifiedOnChanging(value);
					this.SendPropertyChanging();
					this._ModifiedOn = value;
					this.SendPropertyChanged("ModifiedOn");
					this.OnModifiedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(50)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeactivateddOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeactivateddOn
		{
			get
			{
				return this._DeactivateddOn;
			}
			set
			{
				if ((this._DeactivateddOn != value))
				{
					this.OnDeactivateddOnChanging(value);
					this.SendPropertyChanging();
					this._DeactivateddOn = value;
					this.SendPropertyChanged("DeactivateddOn");
					this.OnDeactivateddOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeactivateddBy", DbType="NVarChar(50)")]
		public string DeactivateddBy
		{
			get
			{
				return this._DeactivateddBy;
			}
			set
			{
				if ((this._DeactivateddBy != value))
				{
					this.OnDeactivateddByChanging(value);
					this.SendPropertyChanging();
					this._DeactivateddBy = value;
					this.SendPropertyChanged("DeactivateddBy");
					this.OnDeactivateddByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGoodEmail", DbType="Bit")]
		public System.Nullable<bool> IsGoodEmail
		{
			get
			{
				return this._IsGoodEmail;
			}
			set
			{
				if ((this._IsGoodEmail != value))
				{
					this.OnIsGoodEmailChanging(value);
					this.SendPropertyChanging();
					this._IsGoodEmail = value;
					this.SendPropertyChanged("IsGoodEmail");
					this.OnIsGoodEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLDEmailRating", DbType="Decimal(18,9)")]
		public System.Nullable<decimal> HLDEmailRating
		{
			get
			{
				return this._HLDEmailRating;
			}
			set
			{
				if ((this._HLDEmailRating != value))
				{
					this.OnHLDEmailRatingChanging(value);
					this.SendPropertyChanging();
					this._HLDEmailRating = value;
					this.SendPropertyChanged("HLDEmailRating");
					this.OnHLDEmailRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLDPermissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> HLDPermissionDate
		{
			get
			{
				return this._HLDPermissionDate;
			}
			set
			{
				if ((this._HLDPermissionDate != value))
				{
					this.OnHLDPermissionDateChanging(value);
					this.SendPropertyChanging();
					this._HLDPermissionDate = value;
					this.SendPropertyChanged("HLDPermissionDate");
					this.OnHLDPermissionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLDVerificationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> HLDVerificationDate
		{
			get
			{
				return this._HLDVerificationDate;
			}
			set
			{
				if ((this._HLDVerificationDate != value))
				{
					this.OnHLDVerificationDateChanging(value);
					this.SendPropertyChanging();
					this._HLDVerificationDate = value;
					this.SendPropertyChanged("HLDVerificationDate");
					this.OnHLDVerificationDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLDEmailSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> HLDEmailSent
		{
			get
			{
				return this._HLDEmailSent;
			}
			set
			{
				if ((this._HLDEmailSent != value))
				{
					this.OnHLDEmailSentChanging(value);
					this.SendPropertyChanging();
					this._HLDEmailSent = value;
					this.SendPropertyChanged("HLDEmailSent");
					this.OnHLDEmailSentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.List_ID_1908_for_Ardent")]
	public partial class List_ID_1908_for_Ardent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HLD_ProvID;
		
		private int _NPI;
		
		private string _EMAIL;
		
		private string _ContractType;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHLD_ProvIDChanging(int value);
    partial void OnHLD_ProvIDChanged();
    partial void OnNPIChanging(int value);
    partial void OnNPIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnContractTypeChanging(string value);
    partial void OnContractTypeChanged();
    #endregion
		
		public List_ID_1908_for_Ardent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLD_ProvID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HLD_ProvID
		{
			get
			{
				return this._HLD_ProvID;
			}
			set
			{
				if ((this._HLD_ProvID != value))
				{
					this.OnHLD_ProvIDChanging(value);
					this.SendPropertyChanging();
					this._HLD_ProvID = value;
					this.SendPropertyChanged("HLD_ProvID");
					this.OnHLD_ProvIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NPI", DbType="Int NOT NULL")]
		public int NPI
		{
			get
			{
				return this._NPI;
			}
			set
			{
				if ((this._NPI != value))
				{
					this.OnNPIChanging(value);
					this.SendPropertyChanging();
					this._NPI = value;
					this.SendPropertyChanged("NPI");
					this.OnNPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContractType", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string ContractType
		{
			get
			{
				return this._ContractType;
			}
			set
			{
				if ((this._ContractType != value))
				{
					this.OnContractTypeChanging(value);
					this.SendPropertyChanging();
					this._ContractType = value;
					this.SendPropertyChanged("ContractType");
					this.OnContractTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
